import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/Provider/AuthProvider";
import LayoutWrapper from "@/Components/NavbarToogle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "smart task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthProvider>
      <LayoutWrapper>
      {children}

      </LayoutWrapper>
           <Toaster toastOptions={{
            duration : 2000
           }}/>
         </AuthProvider>
  
      </body>
    </html>
  );
}
